spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@dev.gklqt.com:51521:orcl
    username: nisxy
    password: hncslqt99
    max-idle: 10
    max-wait: 10000
    min-idle: 5
    initial-size: 5
